seed: 42

max_tries: 25

tr_sp:
  max_iter: 40
  improve_ratio_threshold: 0.2
  min_approx_improve: 1.0e-4
  min_approx_improve_frac: 1.0e-3
  trust_shrink_ratio: 0.1
  trust_expand_ratio: 1.5
  max_merit_coeff_iter: 4
  merit_coeff_increase_ratio: 10.0

traj_smooth_term:
  k: 1
  offset: 3
  merit_coeff: 1.0
  threshold: 0.2

base_fixation_term:
  merit_coeff: 20.0
  threshold: 1.0e-4

ee_pose_term:
  merit_coeff: 20.0
  threshold: 1.0e-3

self_collision_term:
  sd_check: 0.1
  sd_safe: 0.05
  merit_coeff: 200.0
  threshold: 1.0e-4
