robot_cfg:
  kinematics:
    urdf_path: "robot/franka_description/franka_w_base.urdf"
    asset_root_path: "robot/franka_description"
    root_link: "root_link"
    base_link: "panda_link0"
    ee_link: "panda_hand"

    collision_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "panda_hand",
      ]

    self_collision_ignore:
      {
        "panda_link0": ["panda_link1", "panda_link2"],
        "panda_link1": ["panda_link2", "panda_link3", "panda_link4"],
        "panda_link2": ["panda_link3", "panda_link4"],
        "panda_link3": ["panda_link4", "panda_link6"],
        "panda_link4":
          ["panda_link5", "panda_link6", "panda_link7", "panda_link8"],
        "panda_link5": ["panda_link6", "panda_link7", "panda_hand"],
        "panda_link6": ["panda_link7", "panda_hand"],
        "panda_link7": ["panda_hand"],
      }

    mesh_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "panda_hand",
      ]

    cspace:
      joint_names:
        [
          "panda_joint1",
          "panda_joint2",
          "panda_joint3",
          "panda_joint4",
          "panda_joint5",
          "panda_joint6",
          "panda_joint7",
        ]
      retract_config: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0.0]
