robot_cfg:
  kinematics:
    urdf_path: "robot/ur10e_description/ur10e.urdf"
    asset_root_path: "robot/ur10e_description"
    root_link: "root_link"
    base_link: "base_link_inertia"
    ee_link: "tool0"

    collision_link_names:
      [
        "base_link_inertia",
        "shoulder_link",
        "upper_arm_link",
        "forearm_link",
        "wrist_1_link",
        "wrist_2_link",
        "wrist_3_link",
      ]

    self_collision_ignore:
      {
        "base_link_inertia":
          [
            "shoulder_link",
            "upper_arm_link",
            "forearm_link",
            "wrist_1_link",
            "wrist_2_link",
            "wrist_3_link",
          ],
        "shoulder_link": ["upper_arm_link"],
        "upper_arm_link": ["forearm_link"],
        "forearm_link": ["wrist_1_link", "wrist_2_link"],
        "wrist_1_link": ["wrist_2_link", "wrist_3_link"],
        "wrist_2_link": ["wrist_3_link"],
      }

    mesh_link_names:
      [
        "base_link_inertia",
        "shoulder_link",
        "upper_arm_link",
        "forearm_link",
        "wrist_1_link",
        "wrist_2_link",
        "wrist_3_link",
      ]

    cspace:
      joint_names:
        [
          "shoulder_pan_joint",
          "shoulder_lift_joint",
          "elbow_joint",
          "wrist_1_joint",
          "wrist_2_joint",
          "wrist_3_joint",
        ]
      retract_config: [0.0, -2.2, 1.9, -1.383, -1.57, 0.0]
